name: Terraform Apply

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_port: ${{ secrets.PORT }}
      TF_VAR_app_keys: ${{ secrets.APP_KEYS }}
      TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
      TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
      TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
      TF_VAR_database_client: ${{ secrets.DATABASE_CLIENT }}
      TF_VAR_database_ssl: ${{ secrets.DATABASE_SSL }}
      TF_VAR_database_filename: ${{ secrets.DATABASE_FILENAME }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_host: ${{ secrets.HOST }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
