name: Terraform Apply

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_env_vars_PORT: ${{ secrets.PORT }}
      TF_VAR_env_vars_APP_KEYS: ${{ secrets.APP_KEYS }}
      TF_VAR_env_vars_API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
      TF_VAR_env_vars_ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
      TF_VAR_env_vars_TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
      TF_VAR_env_vars_DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
      TF_VAR_env_vars_DATABASE_SSL: ${{ secrets.DATABASE_SSL }}
      TF_VAR_env_vars_DATABASE_FILENAME: ${{ secrets.DATABASE_FILENAME }}
      TF_VAR_env_vars_JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
